import { Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");
export default {
  // Colors
  PRIMARY_COLOR: "#E95FA1",
  WHITE_COLOR: "#FFFFFF",
  LIGHT_PRIMARY_COLOR: "#EE86B8",
  DARK_GREY_COLOR: "#1A2026",
  LIGHT_GREY_COLOR: "#58595B",
  FAINT_GREY_COLOR: "#808285",
  FACEBOOK_COLOR: "#3b5998",
  TRANSPARENT: "transparent",
  BLUE_COLOR: "#1771F1",
  DANGER_COLOR: "#FF0000",
  MINT_COLOR: "#00CF91",
  // Values
  BORDER_CURVE: 8,
  BORDER_ROUND: 20,
  BoRDER_CIRCLE: 100,
  // Fonts
  FONT_SIZE_EXTRA_LARGE: 20,
  FONT_SIZE_LARGE: 17,
  FONT_SIZE_NORMAL: 16,
  FONT_SIZE_SMALL: 14,
  FONT_SIZE_EXTRA_SMALL: 12,
  FONT_WEIGHT_HEAVY: "900",
  FONT_WEIGHT_BOLDER: "700",
  FONT_WEIGHT_BOLD: "500",
  FONT_WEIGHT_NORMAL: "400",
  // Dimensions
  HORIZONTAL_MARGIN: 18,
  WIDTH_100: width,
  HEIGHT_100: height,
};
